version: "3.8"

services:
  backend:
    build: ./chat-app-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build: ./chat-app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
